### ISSUE TITLE
[BUG]:Videos cut diagonally

### ISSUE THREAD

**Issue by aro2021** [ikhoeyZX/Vita3K-Android#734]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Affected Build(s)

v12 build 15

### Description of Issue

Videos are cut diagonally, i experienced this in MK9 and Playstation All Stars

![Image](https://github.com/user-attachments/assets/10d9b0b6-d59f-4b34-a4e1-d059b4950493)

### Expected Behavior

The full videos shown

### Reproduction Steps

This happens on normal settings

### Log File

[vita3k.log](https://github.com/user-attachments/files/21204404/vita3k.log)

### System Configuration (please fill)

CPU: Octa-core Max 2.8GHz
GPU/Driver: Mali-G610 MC4
RAM: 12GB and 6GB Memory extension
OS: Android 15, HyperOS 2.0.9.0

**Comment by Odd-Eyes** [comment]
Android 15, thats your answer

**Comment by Jean10000** [comment]
> Android 15, thats your answer

It happens to me as well on Android 14,not only in vídeos,The entire game plays like this,but on Build 14 It Works well

**Comment by ikhoeyZX** [comment]
HyperOS moment

**Comment by smlcr** [comment]
Anbernic RG406H (Unisoc T820) here, Android 13. Nothing to do with HyperOS or Android 15. It's a bug of the latest version of this fork. :) 
On Build 14 it seems to work fine without that cuts, but there's video flickering (which was fixed in build 15). So I think in build 16 we need to have this "Video flickering fix" checkbox, which help us switch between two modes. 
Or video flickering fix is just broken in some way and needs to be fixed.

**Comment by ikhoeyZX** [comment]
Nah
Currently latelest build still broken due glslang and spirv cross issue (opengl broken 100% for now and gravity rush also broken)
Still find way to fix it

**Comment by ghost** [comment]
Any updates?

**Comment by Jean10000** [comment]
> Any updates?

Yes,use this version :

![Image](https://github.com/user-attachments/assets/9fe6f714-3d49-4ed7-bde2-2ba322c05968)

Worked for me :

<img width="1612" height="720" alt="Image" src="https://github.com/user-attachments/assets/1ee640d5-3634-467c-b0df-518ec431ffa2" />
<img width="1612" height="720" alt="Image" src="https://github.com/user-attachments/assets/c2ab6236-a39d-4b46-9a98-98084f9a3334" />
<img width="1612" height="720" alt="Image" src="https://github.com/user-attachments/assets/29fe65d5-658e-43d6-8881-09a0633151bc" />
<img width="1612" height="720" alt="Image" src="https://github.com/user-attachments/assets/51f46e49-816e-4e42-a47c-c9299e89a268" />

**Comment by ghost** [comment]
Oh, @Jean10000 thank you!

**Comment by ikhoeyZX** [comment]
So it fixed now?

**Comment by ghost** [comment]
> So it fixed now?

Yes, I'm playing the same game at 2x and 8x filtering.

**Comment by ikhoeyZX** [comment]
Good
